### ISSUE TITLE
Upgradde : web interface no longer loads

### ISSUE THREAD

**Issue by kazukyakayashi** [YunoHost-Apps/jellyfin-vue_ynh#154]
### Describe the bug

After the upgrade, the interface no longer loads.
![Screenshot 2024-06-15 at 07-40-32 Jellyfin Vue](https://github.com/YunoHost-Apps/jellyfin-vue_ynh/assets/39823221/e1cd694e-5037-4370-a707-a2d564a0ceee)

### Context

- Hardware: OVH (Kimuifi) KS5
- YunoHost version: 11.2.14.1 (stable)
- I have access to my server: yes
- If upgrading, current package version: 2024.06.10~ynh1

### Logs

https://paste.yunohost.org/raw/zivihihicu

**Comment by kazukyakayashi** [comment]
Okay whit the last update, Jellyfin say : «La version du serveur doit être 10.9.4 ou plus haut» but Jellyfin is not up to date.

So the problem isn't with Jellyfin vue itself, but with both (Jellyfin and JellyfinVue), which are no longer compatible, given the versions currently in use.

**Comment by Salamandar** [comment]
Yes indeed. You can either downgrade jellyfin-vue, or try the testing branch of Jellyfin, or wait a bit. Sorry for the issue.
