### ISSUE TITLE
Update 2023.12.11~ynh1 to 2024.01.05~ynh1 fail

### ISSUE THREAD

**Issue by kazukyakayashi** [YunoHost-Apps/jellyfin-vue_ynh#60]
### Describe the bug

Updating Jellyfin-vueto 2024.01.05~ynh1 does not work.

### Context

- Hardware: OVH Kimsufi KS-5 (Intel Xeon E5-1620v2 - 4c/8t - 3.7 GHz/3.9 GHz, 32go RAM)
- YunoHost version: 11.2.9.1 (stable)
- I have access to my server: not at the moment.
- Using, or trying to install package version/branch: 2024.01.05~ynh1
- If upgrading, current package version: 2023.12.11~ynh1

### Logs

https://paste.yunohost.org/raw/azorisabif

**Comment by kazukyakayashi** [comment]
Solved with the last update.

**Comment by Salamandar** [comment]
Oh 😅 sorry about that...
